#!/bin/bash

if [ $# -eq 0 ]; then
    SRC="$(pwd -P)"
else
    SRC="$(cd "$1" && pwd -P)"
fi

printf "\n"
echo "----------------------"
printf "Running\n"
echo "----------------------"
printf "\n\n"

docker run -it --rm -v "$SRC":/usr/src/app "stephentuso/gcc-runner"
